Fix Helm and Add Probe
idealista/prom2teams pull request #224
Opened 2020-10-21 11:47 UTC by Ianwu0812

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
* Remember to set **idealista:develop** as base branch;

### Description of the Change

Add probe into helm deployment

Add liveness and readiness probe to let kubernetes know that
application can not serve.

Fix kubectl get pods in helm note.
It should be app.kubernetes.io/instance but release.

Some env will occurs error when value is empty. Add quote pipeline
in deployment to fix this problem.

### Benefits

Some value in helm can be empty.

Helm note will show correct infomation.

Kubernetes will restart when application occurs error.

### Possible Drawbacks

No

### Applicable Issues

Same as benefit

2020-10-22 10:49 UTC, vicsufer requested changes

2020-10-22 10:49 UTC, vicsufer commented on helm/templates/deployment.yaml
> +          readinessProbe:
Also at #225 we're working on `/alive` and `/ready` endpoints for livesness and readiness probes respectively. Mind changing the tcp probes for http ones?

2020-10-22 10:55 UTC, vicsufer commented
Thanks for taking the time to contribute @Ianwu0812 I've left some comments on your code. 
Also please update the changelog when finish.

2020-10-23 09:04 UTC, vicsufer commented
Looks good to me, please update the CHANGELOG.md and we're ready to go.

2020-10-23 09:07 UTC, vicsufer approved these changes

2020-10-23 12:28 UTC, dortegau approved these changes

2020-11-04 09:21 UTC, vicsufer commented
Ey @Ianwu0812! We really want to merge this feature into stable branches, can you please update the README.md? Thanks!

2020-11-23 09:37 UTC, Ianwu0812 commented
Hi @vicsufer, I have changed the CHANGELOG.md, is that fit your requirement?

2020-11-24 08:18 UTC, vicsufer commented
@Ianwu0812 I can't see any change commited to CHANGELOG.md
https://github.com/idealista/prom2teams/pull/224/files

2021-01-30 09:57 UTC, closed without merging